__all__ = ('COMMAND_INPUT_URL', 'COMMAND_SCHEDULE_ON_WEEK','COMMAND_HELP', )
BOT_NAME = '[club205640140|test_bot_ssau]'
COMMAND_INPUT_URL = BOT_NAME + ' url='
COMMAND_SCHEDULE_ON_WEEK = BOT_NAME + ' расписание на неделю'
COMMAND_HELP = BOT_NAME + ' help'

